---
title: "Claremont Run of X-Men"
author: "Fernando Finotto Visani"
date: "6/30/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

Loading libraries
```{r setup, include=FALSE}
library(tidyverse)
library(tidytuesdayR)
library(scales)
library(ggcharts)
library(waffle)
library(ggthemes)
```

Getting the data
```{r}
#remotes::install_github("malcolmbarrett/claremontrun")
tuesdata <- tidytuesdayR::tt_load(2020, week = 27)

comic_bechdel <- tuesdata$comic_bechdel
characters <- tuesdata$characters
characters_vis <- tuesdata$character_visualization
covers <- tuesdata$covers
issue_collab <- tuesdata$issue_collaborators
locations <- tuesdata$locations
xmen_bechdel <- tuesdata$xmen_bechdel
```

Analyzing the Comic Bechdel test
```{r}
bechdel_by_series <- comic_bechdel %>% 
  filter(!is.na(pass_bechdel)) %>% 
  group_by(series, pass_bechdel) %>% 
  summarise(n = n()) %>% 
  mutate(pct_pass = n / sum(n),
         pct_pass = ifelse(pass_bechdel == "no", pct_pass * -1, pct_pass))


bechdel_by_series %>% 
  ggplot(aes(pct_pass, series, fill = pass_bechdel)) +
  geom_bar(stat = "identity") +
  theme_hermit() +
  scale_fill_manual(values = c("#D1DEDE", "#FCAB64")) +
  scale_x_continuous(breaks = seq(-1, 1, by = .2),
                     labels = c(seq(1, 0, by = -.2), seq(.2, 1, by = .2))) +
  labs(title = "Best comic series that passed in the Bechdel Test",
     x = "Percentage of passing",
     y = "",
     fill = "Passed the test?")
```

Checking the proportion of Bechdel test X-Men passed
```{r}
parts <- xmen_bechdel %>% 
  filter(!is.na(pass_bechdel)) %>% 
  count(pass_bechdel, sort = TRUE) %>% 
  mutate(pass_bechdel = str_replace(pass_bechdel, "yes", "Passed"),
         pass_bechdel = str_replace(pass_bechdel, "no", "Didn't Pass"))

ggplot(parts, aes(fill = pass_bechdel, values = n)) +
  geom_waffle(color = "white", n_rows = 20, size = 1) +
  theme_minimal() +
  scale_fill_manual(values = c("#D1DEDE", "#FCAB64")) +
  theme(panel.grid = element_blank(),
        axis.text = element_blank(),
        legend.position = "bottom",
        legend.title = element_blank(),
        plot.title = element_text(size = 16, face = "bold", hjust = 0.5)) +
  labs(title = "X-Men scored 52% in the Bechdel test")
```

Analyzing characters
```{r}
characters_sum <- characters %>%
  left_join(y = locations, by = "issue") %>% 
  separate(character, into = c("character", "original_name"), sep = " = ") %>% 
  separate(location, into = c("place", "city"), sep = ", ") %>%
  group_by(issue, character, place, context) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE))) %>% 
  mutate(context = str_remove_all(context, "\\*")) %>% 
  mutate(context = str_to_title(context)) %>% 
  filter(!context %in% c("Unknown Time", "Unspecified Time", NA),
         number_of_kills_non_humans < 1000000)

characters_sum %>% 
  filter(number_of_kills_non_humans > 0) %>% 
  group_by(character) %>% 
  summarise(across(where(is.numeric), ~sum(.x, na.rm = TRUE))) %>% 
  mutate(character = fct_reorder(character, number_of_kills_non_humans)) %>% 
  ggplot(aes(number_of_kills_non_humans, character)) +
  geom_point(aes(color = factor(number_of_kills_non_humans)), size = 9) +
  geom_col(aes(fill = factor(number_of_kills_non_humans)), width = 0.05) +
  geom_text(aes(label = number_of_kills_non_humans), color = "white", size = 4, position = position_dodge(0.5)) +
  theme_hermit() +
  theme(legend.position = "none",
        axis.text.x = element_blank()) +
  labs(title = "Which character killed the most of non-human creatures?",
       x = "",
       y = "")

characters_sum %>% 
  ungroup() %>% 
  select(issue, character, number_of_kills_humans, number_of_kills_non_humans) %>% 
  pivot_longer(-c(issue, character), names_to = "names", values_to = "values") %>% 
  mutate(names = str_remove(names, "number_of_kills_"),
         names = str_replace(names, "_", " "),
         names = str_to_title(names)) %>% 
  filter(values > 0) %>% 
  ggplot(aes(issue, values, color = names)) +
  geom_point(size = 7, alpha = 0.75) +
  scale_x_continuous(breaks = seq(100, 275, by = 25)) +
  scale_y_continuous(breaks = seq(0, 30, by = 5)) +
  theme_minimal() +
  theme(panel.grid = element_blank(),
        legend.position = "top",
        legend.title = element_blank(),
        text = element_text(size = 15)) +
  labs(title = "Number of Humans/Non Humans killed by Issue No.",
       x = "Issue No.",
       y = "Kills") +
  scale_color_manual(values = c("#F08700", "#4A5759"))
```



